# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_cards_dlg.ui'
#
# Created: Wed May 20 22:10:55 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AddCardsDlg(object):
    def setupUi(self, AddCardsDlg):
        AddCardsDlg.setObjectName("AddCardsDlg")
        AddCardsDlg.resize(297,175)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(AddCardsDlg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label_2 = QtGui.QLabel(AddCardsDlg)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2,0,0,1,1)
        self.card_types = QtGui.QComboBox(AddCardsDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.card_types.sizePolicy().hasHeightForWidth())
        self.card_types.setSizePolicy(sizePolicy)
        self.card_types.setObjectName("card_types")
        self.gridlayout.addWidget(self.card_types,0,1,1,1)
        self.label = QtGui.QLabel(AddCardsDlg)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label,1,0,1,1)
        self.categories = QtGui.QComboBox(AddCardsDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categories.sizePolicy().hasHeightForWidth())
        self.categories.setSizePolicy(sizePolicy)
        self.categories.setEditable(True)
        self.categories.setObjectName("categories")
        self.gridlayout.addWidget(self.categories,1,1,1,1)
        self.verticalLayout.addLayout(self.gridlayout)
        self.grade_buttons = QtGui.QGroupBox(AddCardsDlg)
        self.grade_buttons.setObjectName("grade_buttons")
        self.vboxlayout = QtGui.QVBoxLayout(self.grade_buttons)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.grade_0_button = QtGui.QPushButton(self.grade_buttons)
        self.grade_0_button.setAutoDefault(False)
        self.grade_0_button.setObjectName("grade_0_button")
        self.hboxlayout.addWidget(self.grade_0_button)
        self.grade_1_button = QtGui.QPushButton(self.grade_buttons)
        self.grade_1_button.setAutoDefault(False)
        self.grade_1_button.setObjectName("grade_1_button")
        self.hboxlayout.addWidget(self.grade_1_button)
        self.line = QtGui.QFrame(self.grade_buttons)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout.addWidget(self.line)
        self.grade_2_button = QtGui.QPushButton(self.grade_buttons)
        self.grade_2_button.setAutoDefault(False)
        self.grade_2_button.setObjectName("grade_2_button")
        self.hboxlayout.addWidget(self.grade_2_button)
        self.grade_3_button = QtGui.QPushButton(self.grade_buttons)
        self.grade_3_button.setAutoDefault(False)
        self.grade_3_button.setObjectName("grade_3_button")
        self.hboxlayout.addWidget(self.grade_3_button)
        self.grade_4_button = QtGui.QPushButton(self.grade_buttons)
        self.grade_4_button.setAutoDefault(False)
        self.grade_4_button.setObjectName("grade_4_button")
        self.hboxlayout.addWidget(self.grade_4_button)
        self.grade_5_button = QtGui.QPushButton(self.grade_buttons)
        self.grade_5_button.setAutoDefault(False)
        self.grade_5_button.setObjectName("grade_5_button")
        self.hboxlayout.addWidget(self.grade_5_button)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.verticalLayout.addWidget(self.grade_buttons)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.preview_button = QtGui.QPushButton(AddCardsDlg)
        self.preview_button.setAutoDefault(False)
        self.preview_button.setObjectName("preview_button")
        self.hboxlayout1.addWidget(self.preview_button)
        spacerItem = QtGui.QSpacerItem(101,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.exit_button = QtGui.QPushButton(AddCardsDlg)
        self.exit_button.setAutoDefault(False)
        self.exit_button.setObjectName("exit_button")
        self.hboxlayout1.addWidget(self.exit_button)
        self.verticalLayout.addLayout(self.hboxlayout1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AddCardsDlg)
        QtCore.QObject.connect(self.card_types,QtCore.SIGNAL("activated(QString)"),AddCardsDlg.update_card_widget)
        QtCore.QObject.connect(self.exit_button,QtCore.SIGNAL("clicked()"),AddCardsDlg.reject)
        QtCore.QObject.connect(self.preview_button,QtCore.SIGNAL("clicked()"),AddCardsDlg.preview)
        QtCore.QMetaObject.connectSlotsByName(AddCardsDlg)

    def retranslateUi(self, AddCardsDlg):
        AddCardsDlg.setWindowTitle(QtGui.QApplication.translate("AddCardsDlg", "Add cards", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddCardsDlg", "Card type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddCardsDlg", "Categories:", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_buttons.setTitle(QtGui.QApplication.translate("AddCardsDlg", "Select initial grade:", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_0_button.setText(QtGui.QApplication.translate("AddCardsDlg", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_0_button.setShortcut(QtGui.QApplication.translate("AddCardsDlg", "Ctrl+0", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_1_button.setText(QtGui.QApplication.translate("AddCardsDlg", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_1_button.setShortcut(QtGui.QApplication.translate("AddCardsDlg", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_2_button.setText(QtGui.QApplication.translate("AddCardsDlg", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_2_button.setShortcut(QtGui.QApplication.translate("AddCardsDlg", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_3_button.setText(QtGui.QApplication.translate("AddCardsDlg", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_3_button.setShortcut(QtGui.QApplication.translate("AddCardsDlg", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_4_button.setText(QtGui.QApplication.translate("AddCardsDlg", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_4_button.setShortcut(QtGui.QApplication.translate("AddCardsDlg", "Ctrl+4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_5_button.setText(QtGui.QApplication.translate("AddCardsDlg", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_5_button.setShortcut(QtGui.QApplication.translate("AddCardsDlg", "Ctrl+5", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_button.setText(QtGui.QApplication.translate("AddCardsDlg", "&Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.exit_button.setText(QtGui.QApplication.translate("AddCardsDlg", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

import mnemosyne_rc
