# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_appearance_dlg.ui'
#
# Created: Wed May 20 22:10:56 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CardAppearanceDlg(object):
    def setupUi(self, CardAppearanceDlg):
        CardAppearanceDlg.setObjectName("CardAppearanceDlg")
        CardAppearanceDlg.resize(343,149)
        self.verticalLayout_2 = QtGui.QVBoxLayout(CardAppearanceDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(CardAppearanceDlg)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.card_types = QtGui.QComboBox(CardAppearanceDlg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.card_types.sizePolicy().hasHeightForWidth())
        self.card_types.setSizePolicy(sizePolicy)
        self.card_types.setObjectName("card_types")
        self.horizontalLayout.addWidget(self.card_types)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_3 = QtGui.QFrame(CardAppearanceDlg)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem,0,0,1,1)
        spacerItem1 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1,0,1,1,1)
        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2,0,2,1,1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(CardAppearanceDlg)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontal_layout_bg_colour = QtGui.QHBoxLayout()
        self.horizontal_layout_bg_colour.setObjectName("horizontal_layout_bg_colour")
        self.bg_label = QtGui.QLabel(CardAppearanceDlg)
        self.bg_label.setObjectName("bg_label")
        self.horizontal_layout_bg_colour.addWidget(self.bg_label)
        self.background_button = QtGui.QPushButton(CardAppearanceDlg)
        self.background_button.setObjectName("background_button")
        self.horizontal_layout_bg_colour.addWidget(self.background_button)
        spacerItem3 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontal_layout_bg_colour.addItem(spacerItem3)
        self.align_label = QtGui.QLabel(CardAppearanceDlg)
        self.align_label.setObjectName("align_label")
        self.horizontal_layout_bg_colour.addWidget(self.align_label)
        self.alignment = QtGui.QComboBox(CardAppearanceDlg)
        font = QtGui.QFont()
        font.setItalic(False)
        self.alignment.setFont(font)
        self.alignment.setObjectName("alignment")
        self.horizontal_layout_bg_colour.addWidget(self.alignment)
        self.verticalLayout.addLayout(self.horizontal_layout_bg_colour)
        self.line_2 = QtGui.QFrame(CardAppearanceDlg)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.OK_button = QtGui.QPushButton(CardAppearanceDlg)
        self.OK_button.setDefault(True)
        self.OK_button.setObjectName("OK_button")
        self.horizontalLayout_5.addWidget(self.OK_button)
        self.preview_button = QtGui.QPushButton(CardAppearanceDlg)
        self.preview_button.setAutoDefault(False)
        self.preview_button.setObjectName("preview_button")
        self.horizontalLayout_5.addWidget(self.preview_button)
        spacerItem4 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.defaults_button = QtGui.QPushButton(CardAppearanceDlg)
        self.defaults_button.setObjectName("defaults_button")
        self.horizontalLayout_5.addWidget(self.defaults_button)
        self.cancel_button = QtGui.QPushButton(CardAppearanceDlg)
        self.cancel_button.setAutoDefault(False)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_5.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(CardAppearanceDlg)
        QtCore.QObject.connect(self.cancel_button,QtCore.SIGNAL("clicked()"),CardAppearanceDlg.reject)
        QtCore.QObject.connect(self.OK_button,QtCore.SIGNAL("clicked()"),CardAppearanceDlg.accept)
        QtCore.QObject.connect(self.preview_button,QtCore.SIGNAL("clicked()"),CardAppearanceDlg.preview)
        QtCore.QObject.connect(self.card_types,QtCore.SIGNAL("currentIndexChanged(QString)"),CardAppearanceDlg.card_type_changed)
        QtCore.QObject.connect(self.background_button,QtCore.SIGNAL("clicked()"),CardAppearanceDlg.update_background_colour)
        QtCore.QObject.connect(self.defaults_button,QtCore.SIGNAL("clicked()"),CardAppearanceDlg.defaults)
        QtCore.QObject.connect(self.alignment,QtCore.SIGNAL("activated(int)"),CardAppearanceDlg.update_alignment)
        QtCore.QMetaObject.connectSlotsByName(CardAppearanceDlg)

    def retranslateUi(self, CardAppearanceDlg):
        CardAppearanceDlg.setWindowTitle(QtGui.QApplication.translate("CardAppearanceDlg", "Card appearance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CardAppearanceDlg", "Card type:", None, QtGui.QApplication.UnicodeUTF8))
        self.bg_label.setText(QtGui.QApplication.translate("CardAppearanceDlg", "Background:", None, QtGui.QApplication.UnicodeUTF8))
        self.background_button.setText(QtGui.QApplication.translate("CardAppearanceDlg", "Set colour", None, QtGui.QApplication.UnicodeUTF8))
        self.align_label.setText(QtGui.QApplication.translate("CardAppearanceDlg", "Alignment:", None, QtGui.QApplication.UnicodeUTF8))
        self.alignment.addItem(QtGui.QApplication.translate("CardAppearanceDlg", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.alignment.addItem(QtGui.QApplication.translate("CardAppearanceDlg", "Center", None, QtGui.QApplication.UnicodeUTF8))
        self.alignment.addItem(QtGui.QApplication.translate("CardAppearanceDlg", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.OK_button.setText(QtGui.QApplication.translate("CardAppearanceDlg", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.preview_button.setText(QtGui.QApplication.translate("CardAppearanceDlg", "&Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.defaults_button.setText(QtGui.QApplication.translate("CardAppearanceDlg", "&Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("CardAppearanceDlg", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))

import mnemosyne_rc
