# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Wed May 20 22:10:55 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(196,211)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/mnemosyne.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,196,25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Deck = QtGui.QMenu(self.menubar)
        self.menu_Deck.setObjectName("menu_Deck")
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(22,22))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea,self.toolBar)
        self.actionActivateCategories = QtGui.QAction(MainWindow)
        self.actionActivateCategories.setObjectName("actionActivateCategories")
        self.actionAddCards = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/add.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionAddCards.setIcon(icon)
        self.actionAddCards.setObjectName("actionAddCards")
        self.actionCleanDuplicates = QtGui.QAction(MainWindow)
        self.actionCleanDuplicates.setObjectName("actionCleanDuplicates")
        self.actionConfiguration = QtGui.QAction(MainWindow)
        self.actionConfiguration.setObjectName("actionConfiguration")
        self.actionDeleteCurrentFact = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/delete.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionDeleteCurrentFact.setIcon(icon)
        self.actionDeleteCurrentFact.setObjectName("actionDeleteCurrentFact")
        self.actionEditCurrentCard = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/edit.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionEditCurrentCard.setIcon(icon)
        self.actionEditCurrentCard.setObjectName("actionEditCurrentCard")
        self.actionEditDeck = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/deck.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionEditDeck.setIcon(icon)
        self.actionEditDeck.setObjectName("actionEditDeck")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionFileExit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/exit.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionFileExit.setIcon(icon)
        self.actionFileExit.setObjectName("actionFileExit")
        self.actionFileNew = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../pixmaps/filenew.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionFileNew.setIcon(icon)
        self.actionFileNew.setObjectName("actionFileNew")
        self.actionFileOpen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/fileopen.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionFileOpen.setIcon(icon)
        self.actionFileOpen.setObjectName("actionFileOpen")
        self.actionFileSave = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/filesave.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionFileSave.setIcon(icon)
        self.actionFileSave.setObjectName("actionFileSave")
        self.actionFileSaveAs = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/filesaveas.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionFileSaveAs.setIcon(icon)
        self.actionFileSaveAs.setObjectName("actionFileSaveAs")
        self.actionHelpAbout = QtGui.QAction(MainWindow)
        self.actionHelpAbout.setObjectName("actionHelpAbout")
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionGettingStarted = QtGui.QAction(MainWindow)
        self.actionGettingStarted.setObjectName("actionGettingStarted")
        self.actionShowStatistics = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mnemosyne/pixmaps/statistics.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionShowStatistics.setIcon(icon)
        self.actionShowStatistics.setObjectName("actionShowStatistics")
        self.actionShowToolbar = QtGui.QAction(MainWindow)
        self.actionShowToolbar.setCheckable(True)
        self.actionShowToolbar.setChecked(True)
        self.actionShowToolbar.setObjectName("actionShowToolbar")
        self.actionTip = QtGui.QAction(MainWindow)
        self.actionTip.setObjectName("actionTip")
        self.actionCardAppearance = QtGui.QAction(MainWindow)
        self.actionCardAppearance.setObjectName("actionCardAppearance")
        self.actionActivatePlugins = QtGui.QAction(MainWindow)
        self.actionActivatePlugins.setObjectName("actionActivatePlugins")
        self.actionCloneCardTypes = QtGui.QAction(MainWindow)
        self.actionCloneCardTypes.setObjectName("actionCloneCardTypes")
        self.menuFile.addAction(self.actionFileNew)
        self.menuFile.addAction(self.actionFileOpen)
        self.menuFile.addAction(self.actionFileSave)
        self.menuFile.addAction(self.actionFileSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileExit)
        self.menu_Deck.addAction(self.actionAddCards)
        self.menu_Deck.addAction(self.actionEditCurrentCard)
        self.menu_Deck.addAction(self.actionDeleteCurrentFact)
        self.menu_Deck.addSeparator()
        self.menu_Deck.addAction(self.actionEditDeck)
        self.menu_Deck.addAction(self.actionCloneCardTypes)
        self.menu_Deck.addAction(self.actionActivateCategories)
        self.menu_Deck.addAction(self.actionCleanDuplicates)
        self.menu_Deck.addSeparator()
        self.menu_Deck.addAction(self.actionShowStatistics)
        self.menu_Settings.addAction(self.actionCardAppearance)
        self.menu_Settings.addAction(self.actionActivatePlugins)
        self.menu_Settings.addAction(self.actionConfiguration)
        self.menu_Help.addAction(self.actionGettingStarted)
        self.menu_Help.addAction(self.actionTip)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionHelpAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Deck.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionAddCards)
        self.toolBar.addAction(self.actionEditCurrentCard)
        self.toolBar.addAction(self.actionDeleteCurrentFact)
        self.toolBar.addAction(self.actionEditDeck)
        self.toolBar.addAction(self.actionShowStatistics)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionAddCards,QtCore.SIGNAL("activated()"),MainWindow.add_cards)
        QtCore.QObject.connect(self.actionFileNew,QtCore.SIGNAL("activated()"),MainWindow.file_new)
        QtCore.QObject.connect(self.actionFileOpen,QtCore.SIGNAL("activated()"),MainWindow.file_open)
        QtCore.QObject.connect(self.actionFileSave,QtCore.SIGNAL("activated()"),MainWindow.file_save)
        QtCore.QObject.connect(self.actionFileSaveAs,QtCore.SIGNAL("activated()"),MainWindow.file_save_as)
        QtCore.QObject.connect(self.actionFileExit,QtCore.SIGNAL("activated()"),MainWindow.close)
        QtCore.QObject.connect(self.actionEditCurrentCard,QtCore.SIGNAL("activated()"),MainWindow.edit_current_card)
        QtCore.QObject.connect(self.actionDeleteCurrentFact,QtCore.SIGNAL("activated()"),MainWindow.delete_current_fact)
        QtCore.QObject.connect(self.actionCardAppearance,QtCore.SIGNAL("activated()"),MainWindow.card_appearance)
        QtCore.QObject.connect(self.actionActivatePlugins,QtCore.SIGNAL("activated()"),MainWindow.activate_plugins)
        QtCore.QObject.connect(self.actionCloneCardTypes,QtCore.SIGNAL("activated()"),MainWindow.manage_card_types)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Mnemosyne", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Deck.setTitle(QtGui.QApplication.translate("MainWindow", "&Deck", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActivateCategories.setText(QtGui.QApplication.translate("MainWindow", "Activate cate&gories", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActivateCategories.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddCards.setText(QtGui.QApplication.translate("MainWindow", "&Add cards", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddCards.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCleanDuplicates.setText(QtGui.QApplication.translate("MainWindow", "&Clean duplicates", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguration.setText(QtGui.QApplication.translate("MainWindow", "&Configure Mnemosyne", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteCurrentFact.setText(QtGui.QApplication.translate("MainWindow", "&Delete current card(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteCurrentFact.setShortcut(QtGui.QApplication.translate("MainWindow", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditCurrentCard.setText(QtGui.QApplication.translate("MainWindow", "&Edit current card", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditCurrentCard.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditDeck.setText(QtGui.QApplication.translate("MainWindow", "Edit &deck", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditDeck.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "&Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileNew.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSave.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save &as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelpAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport.setText(QtGui.QApplication.translate("MainWindow", "&Import", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGettingStarted.setText(QtGui.QApplication.translate("MainWindow", "&Getting started", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowStatistics.setText(QtGui.QApplication.translate("MainWindow", "Show s&tatistics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowStatistics.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShowToolbar.setText(QtGui.QApplication.translate("MainWindow", "Show &toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTip.setText(QtGui.QApplication.translate("MainWindow", "&Tip of the day", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCardAppearance.setText(QtGui.QApplication.translate("MainWindow", "Card &appearance", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActivatePlugins.setText(QtGui.QApplication.translate("MainWindow", "&Activate plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloneCardTypes.setText(QtGui.QApplication.translate("MainWindow", "Clone card &types", None, QtGui.QApplication.UnicodeUTF8))

import mnemosyne_rc
