# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'review_wdgt.ui'
#
# Created: Wed May 20 22:10:55 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ReviewWdgt(object):
    def setupUi(self, ReviewWdgt):
        ReviewWdgt.setObjectName("ReviewWdgt")
        ReviewWdgt.resize(315,373)
        self.verticalLayout_5 = QtGui.QVBoxLayout(ReviewWdgt)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.question_label = QtGui.QLabel(ReviewWdgt)
        self.question_label.setMaximumSize(QtCore.QSize(320,16777215))
        self.question_label.setObjectName("question_label")
        self.verticalLayout.addWidget(self.question_label)
        self.question = QtWebKit.QWebView(ReviewWdgt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question.sizePolicy().hasHeightForWidth())
        self.question.setSizePolicy(sizePolicy)
        self.question.setMinimumSize(QtCore.QSize(295,100))
        self.question.setUrl(QtCore.QUrl("about:blank"))
        self.question.setObjectName("question")
        self.verticalLayout.addWidget(self.question)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.answer_label = QtGui.QLabel(ReviewWdgt)
        self.answer_label.setObjectName("answer_label")
        self.verticalLayout_2.addWidget(self.answer_label)
        self.answer = QtWebKit.QWebView(ReviewWdgt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer.sizePolicy().hasHeightForWidth())
        self.answer.setSizePolicy(sizePolicy)
        self.answer.setMinimumSize(QtCore.QSize(295,100))
        self.answer.setUrl(QtCore.QUrl("about:blank"))
        self.answer.setObjectName("answer")
        self.verticalLayout_2.addWidget(self.answer)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.show_button = QtGui.QPushButton(ReviewWdgt)
        self.show_button.setAutoDefault(True)
        self.show_button.setObjectName("show_button")
        self.verticalLayout_4.addWidget(self.show_button)
        self.grades = QtGui.QGroupBox(ReviewWdgt)
        self.grades.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.grades.setObjectName("grades")
        self._2 = QtGui.QVBoxLayout(self.grades)
        self._2.setObjectName("_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grade_0_button = QtGui.QPushButton(self.grades)
        self.grade_0_button.setAutoDefault(True)
        self.grade_0_button.setObjectName("grade_0_button")
        self.horizontalLayout.addWidget(self.grade_0_button)
        self.grade_1_button = QtGui.QPushButton(self.grades)
        self.grade_1_button.setObjectName("grade_1_button")
        self.horizontalLayout.addWidget(self.grade_1_button)
        self.line = QtGui.QFrame(self.grades)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.grade_2_button = QtGui.QPushButton(self.grades)
        self.grade_2_button.setObjectName("grade_2_button")
        self.horizontalLayout.addWidget(self.grade_2_button)
        self.grade_3_button = QtGui.QPushButton(self.grades)
        self.grade_3_button.setObjectName("grade_3_button")
        self.horizontalLayout.addWidget(self.grade_3_button)
        self.grade_4_button = QtGui.QPushButton(self.grades)
        self.grade_4_button.setAutoDefault(True)
        self.grade_4_button.setDefault(False)
        self.grade_4_button.setObjectName("grade_4_button")
        self.horizontalLayout.addWidget(self.grade_4_button)
        self.grade_5_button = QtGui.QPushButton(self.grades)
        self.grade_5_button.setObjectName("grade_5_button")
        self.horizontalLayout.addWidget(self.grade_5_button)
        self._2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.grades)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)

        self.retranslateUi(ReviewWdgt)
        QtCore.QObject.connect(self.show_button,QtCore.SIGNAL("clicked()"),ReviewWdgt.show_answer)
        QtCore.QMetaObject.connectSlotsByName(ReviewWdgt)

    def retranslateUi(self, ReviewWdgt):
        self.question_label.setText(QtGui.QApplication.translate("ReviewWdgt", "Question:", None, QtGui.QApplication.UnicodeUTF8))
        self.answer_label.setText(QtGui.QApplication.translate("ReviewWdgt", "Answer:", None, QtGui.QApplication.UnicodeUTF8))
        self.show_button.setText(QtGui.QApplication.translate("ReviewWdgt", "Show &answer", None, QtGui.QApplication.UnicodeUTF8))
        self.grades.setTitle(QtGui.QApplication.translate("ReviewWdgt", "Grade your answer:", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_0_button.setText(QtGui.QApplication.translate("ReviewWdgt", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_0_button.setShortcut(QtGui.QApplication.translate("ReviewWdgt", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_1_button.setText(QtGui.QApplication.translate("ReviewWdgt", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_1_button.setShortcut(QtGui.QApplication.translate("ReviewWdgt", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_2_button.setText(QtGui.QApplication.translate("ReviewWdgt", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_2_button.setShortcut(QtGui.QApplication.translate("ReviewWdgt", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_3_button.setText(QtGui.QApplication.translate("ReviewWdgt", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_3_button.setShortcut(QtGui.QApplication.translate("ReviewWdgt", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_4_button.setText(QtGui.QApplication.translate("ReviewWdgt", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_4_button.setShortcut(QtGui.QApplication.translate("ReviewWdgt", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_5_button.setText(QtGui.QApplication.translate("ReviewWdgt", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.grade_5_button.setShortcut(QtGui.QApplication.translate("ReviewWdgt", "5", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
